spring:
  application:
    name: office-parking-planner

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/parkingdb
    username: parking
    password: parking
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080